name: Test

on:
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
      - '**.rst'
      - '**.ipynb'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install tensorflow
          pip install -r requirements.txt
          pip install -r requirements-extras.txt
      - name: Run tests
        run: |
          scripts/test.sh > pytest-coverage.txt 2>&1
          retval=$?
          cat pytest-coverage.txt
          exit $retval
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
